### ISSUE TITLE
how to download the dataset 

### ISSUE THREAD

**Issue by qco-11** [ySalaun/LineSfM#11]
Dear @ySalaun , thank you for share such a nice LineSfM  code.
Recently，I read your paper 《Robust SfM with Little Image Overlap》， I am interested in the indoor dataset of the paper, but I don't know how to download it, can you provide it to me ?

**Comment by ySalaun** [comment]
Hi,
I did not upload the dataset when we published the paper and I think I partially lost it.
I found one set of pictures that I've put [there ](https://github.com/ySalaun/LineSfM/upload/master/TEST_IMAGES/INDOOR_DATASET). Are these the ones you were looking for ?

**Comment by qco-11** [comment]
hello, thanks  for your reply, but I find nothing in that website.
![2022-03-03 21-07-34](https://user-images.githubusercontent.com/67098264/156572275-4e69aace-caec-496b-92df-91fb092736c0.png)

**Comment by ySalaun** [comment]
wrong link
https://github.com/ySalaun/LineSfM/tree/master/TEST_IMAGES/INDOOR_DATASET

**Comment by qco-11** [comment]
Hello, thanks for your help, I download it successfully.
I have a question, the office-p19 means 19 pictures in your paper. Actually I only get 9 pictures from the file you provided.
Maybe you partially lost it.

**Comment by ySalaun** [comment]
It seems it's the only dataset I managed to found back.
I'll have a look in other datastorage I still have in the next few days but I'm not confindent on finding them back.

**Comment by qco-11** [comment]
Okay, I will be deeply appreciated that you have done for me and look forward to your reply.

**Comment by ySalaun** [comment]
I'm sorry I didn't find any related dataset in my old drives.
So I'll close this issue.
