### ISSUE TITLE
runtime error with opencv3.4 

### ISSUE THREAD

**Issue by zebrajack** [ySalaun/LineSfM#2]
DETECT LINES AND COMPUTE DESCRIPTORS
OpenCV Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in resize, file /root/opencv-3.4.0/modules/imgproc/src/resize.cpp, line 4044
terminate called after throwing an instance of 'cv::Exception'
  what():  /root/opencv-3.4.0/modules/imgproc/src/resize.cpp:4044: error: (-215) ssize.width > 0 && ssize.height > 0 in function resize

I have no idea what should I do according to the error.

**Comment by ySalaun** [comment]
Hi,

With this error it is difficult for me to help you.
However I can give you some hints to help you debug:
- it seems that a null image is used somewhere in the code
- could you tell me at which step exactly it fails ?
- are you sure the pictures are loaded well ? the path given is correct ?

Best,

Yohann

**Comment by zebrajack** [comment]
build it in "build" folder and maintained your folder structure.
![image](https://user-images.githubusercontent.com/1118889/37821566-f2b7c662-2ebe-11e8-8579-7a364abe3ef0.png)

![image](https://user-images.githubusercontent.com/1118889/37821708-4fd9abe4-2ebf-11e8-8793-302fac81e756.png)

**Comment by ySalaun** [comment]
Hi,

I think the issue is that it looks for images inside home/yohann/Images folder
You should change images.txt file and replace /home/yohann by the correct path.

Best,

Yohann

**Comment by zebrajack** [comment]
Oh, I didn't get notice. thks.
BTW, I have changed it and relocate to the TEST_IMAGES Folder. and with k.txt file in it. why the Calibration cannot read it directly. Are there some options to read it?
![image](https://user-images.githubusercontent.com/1118889/37833668-da9fdf06-2ee6-11e8-8afc-7f0e64f86845.png)

**Comment by ySalaun** [comment]
The message you sent first has been edited and I'm not sure to understand what you wrote.
Do you still have an issue ?

**Comment by zebrajack** [comment]
Yeah. I mean I didn't get notice the path is absolute path. so I changed it, and now it works for most command. but only the Calibration command doesn't work,I thought it cause by the k.txt , but find it has been read already. but still pop up the core dumped error. I have no idea what happened.

**Comment by ySalaun** [comment]
Have you used openMVG to detect and match points ?
You need to detect and match points one way or another before using the calibration command,
I won't be able to answer you before next Monday,
Hope you it will work,

Best,

Yohann

**Comment by zebrajack** [comment]
Oh, I thought the calibaration should use the line detection and matching which has already runned in advanced. since I intend to use the indoor images which lack feature points.  But anyway, let me try the OpenMVG later. and let you know the results. thanks for your quick response. 

Regards!
Cheng

**Comment by ySalaun** [comment]
Yes,  this method still need a few points in order to compute the relative translation. 
If you want to use line only, you should use trifocal methods.
