### ISSUE TITLE
The PLY seems to be uncorrect

### ISSUE THREAD

**Issue by haopo2005** [ySalaun/LineSfM#3]
Hi,
I have run the full pipeline as your readme said.
The result of reconstruction stage seems uncorret, as followed.
![image](https://user-images.githubusercontent.com/9463657/38566963-927dac6e-3d17-11e8-9a9a-22d984c7db5d.png)
I cant see the structure of the original image from these reconstructed planes.
But I can see the 3d structure from the openMVG pipeline

![openmvg pipeline_20180410234806](https://user-images.githubusercontent.com/9463657/38567797-a8a65b60-3d19-11e8-98d8-20b485bc9a99.gif)

And I'd like to know how to get the 3d lines from the ply file?

Can you have a look at my reconstruction log?
[reconstruction.log](https://github.com/ySalaun/LineSfM/files/1895256/reconstruction.log)

**Comment by ySalaun** [comment]
Hi,

First, note that the reconstruction with 4 pictures is not necessarily dense enough for you to recognise well the scene.
Second, the scene represents two perpendicular walls surroudning a courtyard which seems to be what you obtained in the recpnstruction file.
Third, the plane reconstruction method is far from perfect and if the result doesn't suit you, you can tune some parameters (especially the one used for coplanar constraints merging).

About the 3D lines file, it is supposed to be saved in a file with the same name as the plane file but without "_planes" in the name.

About your log, it seems that everything worked well. In fact, this example is mostly there to help you understand and use the code, not to obtain nice results :)

Best,

Yohann

**Comment by haopo2005** [comment]
thank you so much.
