### ISSUE TITLE
CALIBRATION error

### ISSUE THREAD

**Issue by HollisJoe** [ySalaun/LineSfM#6]
Hi, I use the TEST_IMAGE and use openMVG detections, but the CALIBRATION output this:
4
0000         /home/holy/source/com-InteriorModeling/LineSFMTestData/origin/0000.png
0001         /home/holy/source/com-InteriorModeling/LineSFMTestData/origin/0001.png
0002         /home/holy/source/com-InteriorModeling/LineSFMTestData/origin/0002.png
0003         /home/holy/source/com-InteriorModeling/LineSFMTestData/origin/0003.png
reading intrinsic parameters
reading global poses
computing relative poses
LOAD DETECTIONS AND MATCHES
COMPUTE POSES
PROCESSED IN 3.84876
images 0 and 1
Error in rotation : 120
Error in translation : nan
images 1 and 2
Error in rotation : 120
Error in translation : nan
images 2 and 3
Error in rotation : 120
Error in translation : nan
AVERAGE RESULTS: 
Rotation: 120
Translation: nan

What this Error?

**Comment by HollisJoe** [comment]
The OpenMVG I use this:
OPENMVG_SFM_BIN = "/home/holy/source/com-InteriorModeling/openMVG-1.3/build-src-Desktop-Default/Linux-x86_64-Release"

# Indicate the openMVG camera sensor width directory
CAMERA_SENSOR_WIDTH_DIRECTORY = "/home/holy/source/com-InteriorModeling/openMVG-1.3/src/software/SfM" + "/../../openMVG/exif/sensor_width_database"

import os
import subprocess
import sys

if len(sys.argv) < 3:
    print ("Usage %s image_dir output_dir" % sys.argv[0])
    sys.exit(1)

input_dir = sys.argv[1]
output_dir = sys.argv[2]
matches_dir = os.path.join(output_dir, "matches")
reconstruction_dir = os.path.join(output_dir, "reconstruction_sequential")
camera_file_params = os.path.join(CAMERA_SENSOR_WIDTH_DIRECTORY, "sensor_width_camera_database.txt")

print ("Using input dir  : ", input_dir)
print ("      output_dir : ", output_dir)

# Create the ouput/matches folder if not present
if not os.path.exists(output_dir):
  os.mkdir(output_dir)
if not os.path.exists(matches_dir):
  os.mkdir(matches_dir)

print ("1. Intrinsics analysis")
pIntrisics = subprocess.Popen( [os.path.join(OPENMVG_SFM_BIN, "openMVG_main_SfMInit_ImageListing"),  "-i", input_dir, "-o", matches_dir, "-d", camera_file_params, "-k", "2760;0;1536;0;2760;1024;0;0;1"] )
pIntrisics.wait()

print ("2. Compute features")
pFeatures = subprocess.Popen( [os.path.join(OPENMVG_SFM_BIN, "openMVG_main_ComputeFeatures"),  "-i", matches_dir+"/sfm_data.json", "-o", matches_dir, "-m", "AKAZE_FLOAT"] )
pFeatures.wait()

print ("3. Compute matches")
pMatches = subprocess.Popen( [os.path.join(OPENMVG_SFM_BIN, "openMVG_main_ComputeMatches"),  "-i", matches_dir+"/sfm_data.json", "-o", matches_dir] )
pMatches.wait()

**Comment by ySalaun** [comment]
Hi,

Just to be sure:
- have you also run line_matching ? Did it give you good results ?
- about openMVG, do you have a file called matches.putative.txt in a subfolder called openMVG ? May be you have obtained the good file but did not put it in the good folder ?

I don't really think of other issues but reply me if you still have an issue (be quick though, I am on holidays in 8 hours for a week)

Best,

Yohann

**Comment by HollisJoe** [comment]
Thanks!
que 1. I run line_matching,get the results:
![default](https://user-images.githubusercontent.com/24452259/39038311-c5a12364-44b5-11e8-9f8c-805c9e072e8c.png)
que 2. I give the matches.putative.txt and put it in the good folder:
![default](https://user-images.githubusercontent.com/24452259/39038384-f9ff2200-44b5-11e8-9bb0-37bf48fe60b0.png)
![default](https://user-images.githubusercontent.com/24452259/39038405-0926b98c-44b6-11e8-92ce-da475cfb90c1.png)

**Comment by ySalaun** [comment]
I'm not sure to undertand. Did it work ? You're still having an issue ?

**Comment by HollisJoe** [comment]
Thanks! It still having an issue!
![default](https://user-images.githubusercontent.com/24452259/39042341-20a17ff0-44bd-11e8-9d2c-495bdc3fbb78.png)

**Comment by HollisJoe** [comment]
Thanks! Ii's Worked!
