### ISSUE TITLE
Some code seems useless

### ISSUE THREAD

**Issue by JimZhou-001** [ySalaun/LineSfM#9]
Hello, @ySalaun!

Thank you for your great job on line-based SfM. I'm reading your code and have some doubts.

From line 246 to line 284 in [LineSfM/CALIBRATION/scale_uniformization.cpp](https://github.com/ySalaun/LineSfM/blob/f75fb36885df44f361e5cec42b4d02395c636caf/CALIBRATION/scale_uniformization.cpp#L246), you make a repartition among directions. But the code seems useless.

Firstly, variables `dir_left`, `dir_right`, `proj_left`, `proj_right` and `found` are defined in the function `computeCoplanarCts`. They are never used after line 284.

Secondly, though you modify `cluster_left` and `cluster_right`, which can be used beyond this function, the function `computeCoplanarCts` is only used [once](https://github.com/ySalaun/LineSfM/blob/f75fb36885df44f361e5cec42b4d02395c636caf/CALIBRATION/scale_uniformization.cpp#L741) and these 2 parameters make no sense.

Maybe you wanted to do something, but you forgot?

And actually I don't know what this [repartition](https://github.com/ySalaun/LineSfM/blob/f75fb36885df44f361e5cec42b4d02395c636caf/CALIBRATION/scale_uniformization.cpp#L246) do. Would you mind explaining it to me? Thank you.

Looking forward to your reply.

Sincerely,
Jim

**Comment by ySalaun** [comment]
Hi,

I think that I wanted to do something and maybe I did some test.
However, I cannot tell you what I wanted to do at this time and it would be better to delete it.

Thanks for the remark,

Yohann
